"""Setup operations: optional dependency installs and .env generation."""

import importlib.util
import shutil
import subprocess  # nosec B404
import sys
from pathlib import Path

from py_invoices.constants import APP_NAME, CLI_NAME

BACKENDS = ["files", "sqlite", "postgres", "mysql", "memory"]
FILE_FORMATS = ["json", "xml", "md"]
DEFAULT_STORAGE_PATH = "./data"
DEFAULT_FILE_FORMAT = "md"

_BACKEND_MODULES = {
    "sqlite": ("sqlmodel",),
    "postgres": ("sqlmodel", "psycopg2"),
    "mysql": ("sqlmodel", "pymysql"),
}

_DB_URL_EXAMPLES = {
    "postgres": "postgresql://user:pass@localhost/db",
    "mysql": "mysql://user:pass@localhost/db",
}


def install_package(package: str) -> bool:
    """Install a package using uv (preferred) or pip."""
    uv_path = shutil.which("uv")
    command = (
        [uv_path, "pip", "install", package]
        if uv_path
        else [sys.executable, "-m", "pip", "install", package]
    )
    try:
        subprocess.run(command, check=True, capture_output=True)  # noqa: S603  # nosec B603
    except subprocess.CalledProcessError:
        return False
    return True


def module_available(name: str) -> bool:
    return importlib.util.find_spec(name) is not None


def missing_backend_extra(backend: str) -> str | None:
    """The package extra to install for a SQL backend whose drivers are missing, else None."""
    modules = _BACKEND_MODULES.get(backend)
    if modules is None or all(module_available(m) for m in modules):
        return None
    return f"{APP_NAME}[{backend}]"


def db_url_example(backend: str) -> str:
    return _DB_URL_EXAMPLES.get(backend, "sqlite:///invoices.db")


def env_config_lines(
    backend: str,
    storage_path: str | None,
    file_format: str | None,
    db_url: str | None,
    output_dir: str | None,
) -> list[str]:
    """INVOICES_* assignments for the chosen backend and its settings."""
    lines = [f"INVOICES_BACKEND={backend}"]
    if backend == "files":
        lines.append(f"INVOICES_STORAGE_PATH={storage_path}")
        lines.append(f"INVOICES_FILE_FORMAT={file_format}")
    elif backend in _BACKEND_MODULES and db_url:
        lines.append(f"INVOICES_DATABASE_URL={db_url}")
    if output_dir:
        lines.append(f"INVOICES_OUTPUT_DIR={output_dir}")
    return lines


def write_env_file(path: Path, lines: list[str]) -> None:
    path.write_text(f"# Generated by {CLI_NAME} setup\n" + "\n".join(lines) + "\n")
